#SL Ultimate Control Settings
from consts import ON, OFF

SMART_VIEW = ON
INCLUDE_RETURN_TRACKS = ON
INVERT_MUTE_FEEDBACK = ON
SCENE_FOLLOWS_SESSION_BOX = OFF
TRACK_SELECT_ON_ARM = ON
P2_INVERT_SHIFT_MODE = OFF

DEFAULT_ENCODER_MODE = 8 #0 - Track, 1 - Pan, 2-7 - Send A-F, 8 - Device
DEFAULT_POT_MODE = 2     #0 - Track, 1 - Pan, 2-7 - Send A-F

TEMPO_TOP = 200.0
TEMPO_BOTTOM = 60.0
